In [14]:
from pathlib import Path
import pandas as pd

from decent_bench.utils.checkpoint_manager import CheckpointManager

In [15]:
checkpoint_dir = Path(r"/home/ubuntu/github/decent-bench/examples/nim/results/random/ProxSkip/bs_32")
checkpoint_manager = CheckpointManager(checkpoint_dir)

In [16]:
new_cap = 75

In [17]:
algs = checkpoint_manager.load_initial_algorithms()

In [18]:
metadata = checkpoint_manager.load_metadata()

In [19]:
# if alg == "ProxSkip":
#     # Take first half
#     algorithms = algorithms[: len(algorithms) // 2]
# elif alg == "ProxSkip2":
#     # Take second half
#     algorithms = algorithms[len(algorithms) // 2 :]

In [20]:
metadata["algorithms"] = [alg for alg in metadata["algorithms"] if alg["index"] < new_cap]
checkpoint_manager._save_metadata(metadata)

In [ ]:
new_names = {alg["name"] for alg in metadata["algorithms"]}
algs = [alg for alg in algs if alg.name in new_names]
checkpoint_manager._save_initial_algorithms(algs)

75


In [22]:
len(algs)

75

In [23]:
len(metadata["algorithms"])

75

In [2]:
from pathlib import Path

# iterate through folder and delete all files named checkpoint_0000998.pkl
folder = Path(r"/home/ubuntu/github/decent-bench/examples/nim/results")
s = set()
for file in folder.glob("**/checkpoint_0000998.pkl"):
    file.unlink()
print(s)

set()


In [1]:
from decent_bench.schemes import Quantization
import torch
import numpy as np
import time

q = Quantization(4)
msg = np.random.randn(1000)
msg_torch = torch.from_numpy(msg)

start = time.time()
for _ in range(10000):
    __ = q.compress(msg)
print("Time taken for 10000 compressions:", time.time() - start)

start = time.time()
for _ in range(10000):
    __ = q.compress(msg_torch)
print("Time taken for 10000 compressions:", time.time() - start)

Time taken for 10000 compressions: 0.36625075340270996
Time taken for 10000 compressions: 0.5907175540924072


In [3]:
msg = np.random.randn(4)
msg_torch = torch.from_numpy(msg)
display(msg)
display(q.compress(msg_torch))
q.compress(msg)

array([-0.23633155, -1.70627063, -0.41895053, -0.43563393])

tensor([-0.2363, -1.7060, -0.4190, -0.4356], dtype=torch.float64)

array([-0.2363, -1.706 , -0.419 , -0.4356])

In [4]:
msg = np.random.randn(4)
msg_torch = torch.from_numpy(msg)
display(msg)
display(q.compress(msg_torch))
q.compress(msg)

array([ 0.12231881,  1.66935638, -0.31379957,  1.44345355])

tensor([ 0.1223,  1.6690, -0.3138,  1.4430], dtype=torch.float64)

array([ 0.1223,  1.669 , -0.3138,  1.443 ])